### ISSUE TITLE
Add essential user message

### ISSUE THREAD

**Issue by metacircu1ar** [krillan49/PZDC_dungeon_2#13]
I noticed that the game is missing the following essential message:
```
'Перепутал буквы, ты тупой алкаш -5 жизней -5выносливости -1точность'
```
Because of this the game is currently unplayable. Please fix ASAP.

**Comment by krillan49** [comment]
This is an important part of the project, a special team of 10 developers is responsible for it, so it is simply impossible to miss it or make mistakes.

/controllers/characters/hero_creator.rb   line 56
@messages.main = 'You mixed up the letters, you stupid drunk -5 lives -5 stamina -10 accuracy'
